### ISSUE TITLE
subs box parsing

### ISSUE THREAD

**Issue by bbert** [madebyhiro/codem-isoboxer#19] opened 2016-11-29 14:02 UTC
Hi,
@tieleman @TobbeMobiTV 
For 'subs' box it seems that the parsing function is more than simple parsing regarding ISO/IEC 14496-12 specification. The function does parsing and also interpets/translates the parsing by only storing 'samples_with_subsamples'.
To my mind, this is out of scope of this library. For 'subs' box I would have written the parsing function this way:

    ISOBox.prototype._boxParsers['subs'] = function () {
        this._parseFullBox();
        this.entry_count = this._readUint(32);
        this.entries = [];
        for (var i = 0; i < this.entry_count; i++) {
            var entry = {};
            entry.sample_delta = this._readUint(32);
            entry.subsample_count = this._readUint(16);
            entry.subsamples = [];
            for (var j = 0; j < sample.subsample_count; j++) {
                var subsample = {};
                if (this.version & 0x1) {
                    subsample.subsample_size = this._readUint(32);
                } else {
                    subsample.subsample_size = this._readUint(16);
                }
                subsample.priority = this._readUint(8);
                subsample.discardable = this._readUint(8);
                subsample.codec_specific_parameters = this._readUint(32);
                entry.subsamples.push(subsample);
            }
            this.entries.push(entry);
        }
    }

Let me know if you agree so that I make a PR.

**Comment by TobbeEdgeware** [comment] 2016-11-29 14:20
I agree that it is not a direct mapping of the standard text, but no information is discarded and subsample_count is even redundant given the length of the subsamples list.

That said, I think it's up to @tieleman to decide on whether the code should be change according to your proposal and have the same fields as the standard.

**Comment by bbert** [comment] 2016-11-29 15:02
Yes, some information are discarded:
- entries that do not have subsamples
- the sample_delta field

**Comment by TobbeEdgeware** [comment] 2016-11-29 15:08
I don't agree that any information is gone. Samples without samples are not listed. The whole purpose of the sample_delta field is to jump to the next sample which has subsamples. The one without subsamples are not included. The segment number I introduced therefore conveys the same info as the sum of the previous sample_deltas.

But sure, one can leave this to the next level in the chain.

**Comment by tieleman** [comment] 2016-11-29 18:38
Hi, thanks for raising this issue. By design I thought of codem-isoboxer as just following the ISOBMFF spec as closely as possible, so if the `subs` box contains fields that are not part of the spec I'd prefer to remove them, as not to let the project bloat over time with extra features. It must have slipped past me (and I don't always have the spec right at hand).

So if we'd look at the spec syntax (ISO/IEC 14496-12:2015 - 8.7.7.2), it should probably be changed that:

* Subsamples should only be set if `subsample_count > 0` (I don't know if that's really relevant, but the spec defines it explicitly)
* `subsample.priority` should be `subsample.subsample_priority` (see `subsample.subsample_size`, which already does this)
* `codec_specific_parameters` should be called `reserved`

And while `subsample_count` is actually redundant (as are a lot of the `*_count` attributes), the spec says we should include them, so why not. Just as that entries without subsamples should still be included (which they are judging from the parser).

Am I missing something?

**Comment by TobbeEdgeware** [comment] 2016-11-30 09:52
Looks good to me. I made a corresponding test, so that should be updated as well. @bbert, if you want to make a PR, it's fine with me? Otherwise, I can fix the code I wrote.

**Comment by bbert** [comment] 2016-11-30 10:46
No pb, I will do the PR

**Comment by tieleman** [comment] 2016-12-02 08:38
Closed in 150c05081b707c56b09953abd6bf1211c2c0f72e

**Closed by tieleman** 2016-12-02 08:38 UTC
